/-
Divisor-sublattice averaging projector on `ZMod g`
(the Sublattice-projector proposition of the shadow packetization companions).

For `d ∣ g` the coordinate average steps by `d` (there are `g / d` points in each
averaging class), while the retained Fourier subgroup `H_d` is the one generated
by `g / d`, which has exactly `d` elements.  This orientation is the paper's and
is preserved verbatim here.

Scope of this phase: the finite projector proposition only — the subgroup
description and its cardinality, the exact `1/(g/d) = d/g` normalization, the
apply lemma, the on/off Fourier support theorems, idempotence as an equality of
functions, and off-support vanishing.  Nothing here about nonlinear convolution
closure, logarithm convergence, all-order analytic cancellation, positivity of
projected packets, or generic packets being supported in a proper sublattice.
-/
import RequestProject.IFFTIteratedFlow

open scoped BigOperators

namespace ResidueSlices

/-- The divisor sublattice generated by g/d in ZMod g. -/
def divisorSublattice (g d : ℕ) : AddSubgroup (ZMod g) :=
  AddSubgroup.zmultiples (g / d : ZMod g)

/-- Coordinate averaging over one residue class modulo d. -/
noncomputable def sublatticeProjector {g : ℕ} [NeZero g]
    (d : ℕ) (f : ZMod g → ℂ) : ZMod g → ℂ :=
  fun r =>
    ((g / d : ℕ) : ℂ)⁻¹ *
      ∑ ell : Fin (g / d), f (r + (ell.val * d : ℕ))

/-- `ZMod g` is finite for `NeZero g`, hence so is every subgroup; this instance
only exists to give `Fintype.card (divisorSublattice g d)` a meaning (the value
of `Fintype.card` does not depend on the chosen instance). -/
noncomputable instance divisorSublattice.instFintype (g d : ℕ) [NeZero g] :
    Fintype (divisorSublattice g d) :=
  Fintype.ofFinite _

theorem divisor_pos_of_dvd
    {g d : ℕ} [NeZero g] (hd : d ∣ g) : 0 < d := by
  rcases Nat.eq_zero_or_pos d with h | h
  · exact absurd (by simpa [h] using hd) (NeZero.ne g)
  · exact h

theorem divisor_quotient_pos
    {g d : ℕ} [NeZero g] (hd : d ∣ g) : 0 < g / d :=
  Nat.div_pos (Nat.le_of_dvd (Nat.pos_of_ne_zero (NeZero.ne g)) hd)
    (divisor_pos_of_dvd hd)

/-- `d * (g / d) = g` for `d ∣ g`. -/
theorem divisor_mul_quotient
    {g d : ℕ} [NeZero g] (hd : d ∣ g) : d * (g / d) = g :=
  Nat.mul_div_cancel' hd

/-- `d` annihilates the generator `g / d` of the divisor sublattice. -/
theorem divisor_mul_quotient_cast_eq_zero
    {g d : ℕ} [NeZero g] (hd : d ∣ g) :
    (d : ZMod g) * ((g / d : ℕ) : ZMod g) = 0 := by
  rw [← Nat.cast_mul, divisor_mul_quotient hd, ZMod.natCast_self]

/-- If `d` annihilates `k`, then `g / d` divides the representative of `k`. -/
theorem divisor_quotient_dvd_val
    {g d : ℕ} [NeZero g] (hd : d ∣ g) {k : ZMod g}
    (h : (d : ZMod g) * k = 0) : (g / d) ∣ k.val := by
  have hcast : ((d * k.val : ℕ) : ZMod g) = 0 := by
    push_cast
    rw [ZMod.natCast_zmod_val]
    exact h
  have hdvd : g ∣ d * k.val := (ZMod.natCast_eq_zero_iff _ _).mp hcast
  have hdvd' : d * (g / d) ∣ d * k.val := by
    rw [divisor_mul_quotient hd]
    exact hdvd
  exact (Nat.mul_dvd_mul_iff_left (divisor_pos_of_dvd hd)).mp hdvd'

/-- Membership in the divisor sublattice is exactly annihilation by `d`. -/
theorem mem_divisorSublattice_iff_smul_eq_zero
    {g d : ℕ} [NeZero g] (hd : d ∣ g) (k : ZMod g) :
    k ∈ divisorSublattice g d ↔ (d : ZMod g) * k = 0 := by
  constructor
  · intro hk
    obtain ⟨z, hz⟩ := AddSubgroup.mem_zmultiples_iff.mp hk
    rw [← hz, zsmul_eq_mul]
    calc (d : ZMod g) * ((z : ZMod g) * ((g / d : ℕ) : ZMod g))
        = (z : ZMod g) * ((d : ZMod g) * ((g / d : ℕ) : ZMod g)) := by ring
      _ = 0 := by rw [divisor_mul_quotient_cast_eq_zero hd, mul_zero]
  · intro h
    obtain ⟨a, ha⟩ := divisor_quotient_dvd_val hd h
    refine AddSubgroup.mem_zmultiples_iff.mpr ⟨(a : ℤ), ?_⟩
    have hk : ((a * (g / d) : ℕ) : ZMod g) = k := by
      rw [mul_comm, ← ha, ZMod.natCast_zmod_val]
    rw [zsmul_eq_mul]
    push_cast at hk ⊢
    rw [← hk]

theorem mem_divisorSublattice_iff
    {g d : ℕ} [NeZero g] (hd : d ∣ g) (k : ZMod g) :
    k ∈ divisorSublattice g d ↔
      ∃ a : Fin d, k = (a.val * (g / d) : ℕ) := by
  rw [mem_divisorSublattice_iff_smul_eq_zero hd]
  constructor
  · intro h
    obtain ⟨a, ha⟩ := divisor_quotient_dvd_val hd h
    have haltd : a < d := by
      have hv : (g / d) * a < g := by
        rw [← ha]
        exact ZMod.val_lt k
      have hg : (g / d) * d = g := by
        rw [mul_comm]
        exact divisor_mul_quotient hd
      have hlt : (g / d) * a < (g / d) * d := by
        rw [hg]
        exact hv
      exact Nat.lt_of_mul_lt_mul_left hlt
    refine ⟨⟨a, haltd⟩, ?_⟩
    rw [mul_comm, ← ha, ZMod.natCast_zmod_val]
  · rintro ⟨a, rfl⟩
    push_cast
    calc (d : ZMod g) * ((a.val : ZMod g) * ((g / d : ℕ) : ZMod g))
        = (a.val : ZMod g) * ((d : ZMod g) * ((g / d : ℕ) : ZMod g)) := by ring
      _ = 0 := by rw [divisor_mul_quotient_cast_eq_zero hd, mul_zero]

theorem card_divisorSublattice
    {g d : ℕ} [NeZero g] (hd : d ∣ g) :
    Fintype.card (divisorSublattice g d) = d := by
  have hm : 0 < g / d := divisor_quotient_pos hd
  have hmem : ∀ a : Fin d,
      (((a.val * (g / d) : ℕ) : ZMod g)) ∈ divisorSublattice g d := by
    intro a
    exact (mem_divisorSublattice_iff hd _).mpr ⟨a, rfl⟩
  set F : Fin d → divisorSublattice g d := fun a => ⟨_, hmem a⟩
  have hbij : Function.Bijective F := by
    constructor
    · intro a b hab
      have hval : ((a.val * (g / d) : ℕ) : ZMod g) = ((b.val * (g / d) : ℕ) : ZMod g) :=
        congrArg Subtype.val hab
      have hlt : ∀ c : Fin d, c.val * (g / d) < g := by
        intro c
        calc c.val * (g / d) < d * (g / d) := mul_lt_mul_of_pos_right c.isLt hm
          _ = g := divisor_mul_quotient hd
      have := congrArg ZMod.val hval
      rw [ZMod.val_natCast_of_lt (hlt a), ZMod.val_natCast_of_lt (hlt b)] at this
      exact Fin.ext (Nat.eq_of_mul_eq_mul_right hm this)
    · rintro ⟨k, hk⟩
      obtain ⟨a, ha⟩ := (mem_divisorSublattice_iff hd k).mp hk
      exact ⟨a, Subtype.ext ha.symm⟩
  have := Fintype.card_of_bijective hbij
  simpa using this.symm

theorem sublatticeProjector_normalization
    {g d : ℕ} [NeZero g] (hd : d ∣ g) :
    ((g / d : ℕ) : ℂ)⁻¹ = (d : ℂ) / (g : ℂ) := by
  have hgd : (g : ℂ) = (d : ℂ) * ((g / d : ℕ) : ℂ) := by
    exact_mod_cast congrArg (Nat.cast : ℕ → ℂ) (divisor_mul_quotient hd).symm
  have hd0 : (d : ℂ) ≠ 0 := Nat.cast_ne_zero.mpr (divisor_pos_of_dvd hd).ne'
  have hm0 : ((g / d : ℕ) : ℂ) ≠ 0 :=
    Nat.cast_ne_zero.mpr (divisor_quotient_pos hd).ne'
  rw [hgd]
  field_simp

theorem sublatticeProjector_apply
    {g d : ℕ} [NeZero g] (f : ZMod g → ℂ) (r : ZMod g) :
    sublatticeProjector d f r =
      ((g / d : ℕ) : ℂ)⁻¹ *
        ∑ ell : Fin (g / d), f (r + (ell.val * d : ℕ)) := rfl

/-- Translating the argument of a `positiveDFT` sum by `c` multiplies it by the
character value at `-(c * k)`. -/
theorem positiveDFT_translate
    {g : ℕ} [NeZero g] (f : ZMod g → ℂ) (k c : ZMod g) :
    ∑ j : ZMod g, ZMod.stdAddChar (j * k) * f (j + c) =
      ZMod.stdAddChar (-(c * k)) * ∑ j : ZMod g, ZMod.stdAddChar (j * k) * f j := by
  rw [Finset.mul_sum]
  refine Fintype.sum_equiv (Equiv.addRight c) _ _ ?_
  intro j
  have hchar : ZMod.stdAddChar (-(c * k)) * ZMod.stdAddChar ((j + c) * k) =
      ZMod.stdAddChar (j * k) := by
    rw [← AddChar.map_add_eq_mul]
    congr 1
    ring
  simp only [Equiv.coe_addRight]
  rw [← hchar]
  ring

/-- The Fourier transform of an averaged function factors as a character average
times the Fourier transform of the original function. -/
theorem positiveDFT_sublatticeProjector_factor
    {g d : ℕ} [NeZero g] (f : ZMod g → ℂ) (k : ZMod g) :
    positiveDFT (sublatticeProjector d f) k =
      ((g / d : ℕ) : ℂ)⁻¹ *
        ((∑ ell : Fin (g / d),
            ZMod.stdAddChar (-(((ell.val * d : ℕ) : ZMod g) * k))) *
          positiveDFT f k) := by
  have key : ∀ j : ZMod g,
      ZMod.stdAddChar (j * k) *
          (((g / d : ℕ) : ℂ)⁻¹ * ∑ ell : Fin (g / d), f (j + (ell.val * d : ℕ))) =
        ∑ ell : Fin (g / d),
          ((g / d : ℕ) : ℂ)⁻¹ *
            (ZMod.stdAddChar (j * k) * f (j + (ell.val * d : ℕ))) := by
    intro j
    rw [Finset.mul_sum, Finset.mul_sum]
    exact Finset.sum_congr rfl fun ell _ => by ring
  simp only [positiveDFT, sublatticeProjector]
  rw [Finset.sum_congr rfl fun j _ => key j, Finset.sum_comm, Finset.sum_mul,
    Finset.mul_sum]
  refine Finset.sum_congr rfl fun ell _ => ?_
  rw [← Finset.mul_sum, positiveDFT_translate f k ((ell.val * d : ℕ) : ZMod g)]

/-- On the retained subgroup the character average is the full class size. -/
theorem divisorSublattice_char_sum_of_smul_eq_zero
    {g d : ℕ} [NeZero g] {k : ZMod g} (hk : (d : ZMod g) * k = 0) :
    (∑ ell : Fin (g / d),
        ZMod.stdAddChar (-(((ell.val * d : ℕ) : ZMod g) * k))) = ((g / d : ℕ) : ℂ) := by
  have hone : ∀ ell : Fin (g / d),
      ZMod.stdAddChar (-(((ell.val * d : ℕ) : ZMod g) * k)) = (1 : ℂ) := by
    intro ell
    have hzero : (((ell.val * d : ℕ) : ZMod g) * k) = 0 := by
      push_cast
      calc (ell.val : ZMod g) * (d : ZMod g) * k
          = (ell.val : ZMod g) * ((d : ZMod g) * k) := by ring
        _ = 0 := by rw [hk, mul_zero]
    rw [hzero, neg_zero, AddChar.map_zero_eq_one]
  rw [Finset.sum_congr rfl fun ell _ => hone ell, Finset.sum_const, Finset.card_univ,
    Fintype.card_fin, nsmul_eq_mul, mul_one]

/-- Off the retained subgroup the character average vanishes. -/
theorem divisorSublattice_char_sum_of_smul_ne_zero
    {g d : ℕ} [NeZero g] (hd : d ∣ g) {k : ZMod g} (hk : (d : ZMod g) * k ≠ 0) :
    (∑ ell : Fin (g / d),
        ZMod.stdAddChar (-(((ell.val * d : ℕ) : ZMod g) * k))) = 0 := by
  set w : ℂ := ZMod.stdAddChar (-((d : ZMod g) * k)) with hw
  have hterm : ∀ ell : Fin (g / d),
      ZMod.stdAddChar (-(((ell.val * d : ℕ) : ZMod g) * k)) = w ^ ell.val := by
    intro ell
    rw [hw, ← AddChar.map_nsmul_eq_pow]
    congr 1
    rw [nsmul_eq_mul]
    push_cast
    ring
  have hw1 : w ≠ 1 := by
    intro h
    refine hk ?_
    have hzero : (-((d : ZMod g) * k)) = 0 := by
      apply ZMod.injective_stdAddChar
      rw [← hw, h, AddChar.map_zero_eq_one]
    simpa [neg_eq_zero] using hzero
  have hwm : w ^ (g / d) = 1 := by
    rw [hw, ← AddChar.map_nsmul_eq_pow]
    have hzero : ((g / d : ℕ)) • (-((d : ZMod g) * k)) = 0 := by
      rw [nsmul_eq_mul]
      have : ((g / d : ℕ) : ZMod g) * (d : ZMod g) = 0 := by
        rw [← Nat.cast_mul, mul_comm, divisor_mul_quotient hd, ZMod.natCast_self]
      calc ((g / d : ℕ) : ZMod g) * (-((d : ZMod g) * k))
          = -((((g / d : ℕ) : ZMod g) * (d : ZMod g)) * k) := by ring
        _ = 0 := by rw [this, zero_mul, neg_zero]
    rw [hzero, AddChar.map_zero_eq_one]
  calc (∑ ell : Fin (g / d), ZMod.stdAddChar (-(((ell.val * d : ℕ) : ZMod g) * k)))
      = ∑ ell : Fin (g / d), w ^ ell.val := Finset.sum_congr rfl fun ell _ => hterm ell
    _ = ∑ i ∈ Finset.range (g / d), w ^ i := Fin.sum_univ_eq_sum_range (fun i => w ^ i) _
    _ = (w ^ (g / d) - 1) / (w - 1) := geom_sum_eq hw1 _
    _ = 0 := by rw [hwm]; simp

theorem positiveDFT_sublatticeProjector_of_mem
    {g d : ℕ} [NeZero g] (hd : d ∣ g)
    (f : ZMod g → ℂ) {k : ZMod g}
    (hk : k ∈ divisorSublattice g d) :
    positiveDFT (sublatticeProjector d f) k = positiveDFT f k := by
  have hk' : (d : ZMod g) * k = 0 := (mem_divisorSublattice_iff_smul_eq_zero hd k).mp hk
  have hm0 : ((g / d : ℕ) : ℂ) ≠ 0 :=
    Nat.cast_ne_zero.mpr (divisor_quotient_pos hd).ne'
  rw [positiveDFT_sublatticeProjector_factor f k,
    divisorSublattice_char_sum_of_smul_eq_zero hk', ← mul_assoc,
    inv_mul_cancel₀ hm0, one_mul]

theorem positiveDFT_sublatticeProjector_of_not_mem
    {g d : ℕ} [NeZero g] (hd : d ∣ g)
    (f : ZMod g → ℂ) {k : ZMod g}
    (hk : k ∉ divisorSublattice g d) :
    positiveDFT (sublatticeProjector d f) k = 0 := by
  have hk' : (d : ZMod g) * k ≠ 0 := by
    intro h
    exact hk ((mem_divisorSublattice_iff_smul_eq_zero hd k).mpr h)
  rw [positiveDFT_sublatticeProjector_factor f k,
    divisorSublattice_char_sum_of_smul_ne_zero hd hk', zero_mul, mul_zero]

/-- The averaging sum is invariant under a shift of the base point by a multiple
of `d`. -/
theorem sublatticeProjector_sum_shift
    {g d : ℕ} [NeZero g] (hd : d ∣ g) (f : ZMod g → ℂ) (r : ZMod g) (t : ℕ) :
    ∑ ell : Fin (g / d), f (r + ((t * d : ℕ) : ZMod g) + (ell.val * d : ℕ)) =
      ∑ ell : Fin (g / d), f (r + (ell.val * d : ℕ)) := by
  have hm : 0 < g / d := divisor_quotient_pos hd
  refine Fintype.sum_bijective
    (fun ell : Fin (g / d) => (⟨(ell.val + t) % (g / d), Nat.mod_lt _ hm⟩ : Fin (g / d)))
    ?_ _ _ ?_
  · refine Finite.injective_iff_bijective.mp ?_
    intro a b hab
    have h : (a.val + t) % (g / d) = (b.val + t) % (g / d) := congrArg Fin.val hab
    have hmod : a.val % (g / d) = b.val % (g / d) :=
      (Nat.ModEq.add_right_cancel' t h)
    rw [Nat.mod_eq_of_lt a.isLt, Nat.mod_eq_of_lt b.isLt] at hmod
    exact Fin.ext hmod
  · intro ell
    have hkey :
        ((ell.val + t) % (g / d)) * d + ((ell.val + t) / (g / d)) * g = (ell.val + t) * d := by
      calc ((ell.val + t) % (g / d)) * d + ((ell.val + t) / (g / d)) * g
          = ((ell.val + t) % (g / d)) * d + ((ell.val + t) / (g / d)) * ((g / d) * d) := by
            rw [mul_comm (g / d) d, divisor_mul_quotient hd]
        _ = ((g / d) * ((ell.val + t) / (g / d)) + (ell.val + t) % (g / d)) * d := by ring
        _ = (ell.val + t) * d := by rw [Nat.div_add_mod]
    have hcast : ((((ell.val + t) % (g / d)) * d : ℕ) : ZMod g)
        = (((ell.val + t) * d : ℕ) : ZMod g) := by
      have := congrArg (fun n : ℕ => (n : ZMod g)) hkey
      push_cast at this
      simpa [ZMod.natCast_self] using this
    congr 1
    rw [hcast]
    push_cast
    ring

theorem sublatticeProjector_idempotent
    {g d : ℕ} [NeZero g] (hd : d ∣ g) (f : ZMod g → ℂ) :
    sublatticeProjector d (sublatticeProjector d f) =
      sublatticeProjector d f := by
  have hm0 : ((g / d : ℕ) : ℂ) ≠ 0 :=
    Nat.cast_ne_zero.mpr (divisor_quotient_pos hd).ne'
  funext r
  simp only [sublatticeProjector]
  rw [Finset.sum_congr rfl fun ell (_ : ell ∈ Finset.univ) =>
    congrArg (fun s : ℂ => ((g / d : ℕ) : ℂ)⁻¹ * s)
      (sublatticeProjector_sum_shift hd f r ell.val)]
  rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul]
  field_simp

theorem positiveDFT_sublatticeProjector_supported
    {g d : ℕ} [NeZero g] (hd : d ∣ g) (f : ZMod g → ℂ) :
    ∀ k, k ∉ divisorSublattice g d →
      positiveDFT (sublatticeProjector d f) k = 0 :=
  fun _ hk => positiveDFT_sublatticeProjector_of_not_mem hd f hk

end ResidueSlices
