import Mathlib
import RequestProject.ResidueSlices
import RequestProject.GeneralResidueConvergence
import RequestProject.QuantitativeSpectralGap
import RequestProject.ExplicitSpectralRate
import RequestProject.RpowCorollaries
import RequestProject.HeadTailZeta
import RequestProject.SpinFactorCrossNorm
import RequestProject.DiagonalZeta
import RequestProject.ReversedApproximants
import RequestProject.RationalZeta
import RequestProject.CompactUniform
import RequestProject.ReversedRate
import RequestProject.ResidualCertificate
import RequestProject.SlitPlane
import RequestProject.SlitPlaneReversed
import RequestProject.MetallicCutoff
import RequestProject.BinomialLogConvergence
import RequestProject.IFFTPreparation
import RequestProject.PacketHighPass
import RequestProject.PacketDerivativeJet
import RequestProject.PacketHighPassDivided
import RequestProject.IFFTSupportFlow
import RequestProject.IFFTCoordinateBridge
import RequestProject.IFFTIteratedFlow
import RequestProject.SilverFiniteRowBridge
import RequestProject.SilverFiniteRowRemainder
import RequestProject.SilverFiniteRowFixedPoint
import RequestProject.SilverFiniteRowElasticity
import RequestProject.SilverFiniteRowUnique
import RequestProject.SliceHyperbolic
import RequestProject.SliceMultisection
import RequestProject.SliceFilter
import RequestProject.Gudermann3
import RequestProject.Gudermann4
import RequestProject.GdgCriticalTetranomial
import RequestProject.GdgCriticalCandidateLocation
import RequestProject.GdgCriticalValueSeparation
import RequestProject.GdgLobeTranslation
import RequestProject.GdgNaturalLobes
import RequestProject.GdgRetainedLobes
import RequestProject.GdgZeroClassification
import RequestProject.GdgSignedLobes
import RequestProject.GdgCriticalBridge
import RequestProject.GdgCriticalNoCommonRoot
import RequestProject.GdgCriticalPolynomial
import RequestProject.GdgForcedQuadratic
import RequestProject.GdgReciprocalResidual
import RequestProject.GdgBlockDescent
import RequestProject.GdgBlockRootBridge
import RequestProject.GdgExteriorRoot
import RequestProject.GdgDegreeExhaustion
import RequestProject.GdgLobeUniqueness
import RequestProject.GdgCriticalValueOrdering
import RequestProject.GdgCriticalValuePairwise
import RequestProject.GdgExteriorValueMaximum
import RequestProject.GdgExteriorInteriorOdd
import RequestProject.GdgExteriorInteriorNoncollision
import RequestProject.SilverCrossover

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 8000000
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

set_option pp.fullNames true
set_option pp.structureInstances true
set_option pp.coercions.types true
set_option pp.funBinderTypes true
set_option pp.letVarTypes true
set_option pp.piBinderTypes true

set_option grind.warning false
