/-
Metallic cutoff Phase C3: transverse scale and the canonical metallic cutoff.

The moving-pole laws (MetallicCutoff.tendsto_even_moving_pole_signed /
tendsto_even_moving_pole) give, for B^(2m)*epsilon(m) -> c with c != 0, the
scaled limits (2m)*ratio(-1+epsilon(m),2m)/B^(2m) -> 4/c and the absolute
companion -> 4/|c|. MetallicFixedPointSharp gives
spectralBase^(2m)*(evenFixedPoint m - silver) -> 4*silver.

This final phase defines the transverse channel generated by the canonical
fixed point, proves its scaled perturbation tends to -8, and instantiates the
moving-pole theorems to obtain the signed cutoff -1/2 and absolute cutoff 1/2.
-/
import RequestProject.MetallicFixedPointSharp

open Filter

namespace MetallicCutoff

noncomputable def evenFixedPointTransversePerturbation (m : ℕ) : ℝ :=
  2 - beta * evenFixedPoint m

noncomputable def evenFixedPointTransverseDelta (m : ℕ) : ℝ :=
  1 - beta * evenFixedPoint m

theorem evenFixedPointTransversePerturbation_eq (m : ℕ) :
    evenFixedPointTransversePerturbation m =
      -beta * (evenFixedPoint m - silver) := by
  have hbs : beta * silver = 2 := silver_identities.2.1
  simp only [evenFixedPointTransversePerturbation]
  linear_combination -hbs

theorem evenFixedPointTransverseDelta_lt_neg_one {m : ℕ} (hm : 1 ≤ m) :
    evenFixedPointTransverseDelta m < -1 := by
  have hbs : beta * silver = 2 := silver_identities.2.1
  have hspos : 0 < silver := silver_identities.1
  have hbeta : 0 < beta := by
    unfold beta
    exact div_pos (by norm_num) hspos
  have hlt : silver < evenFixedPoint m := silver_lt_evenFixedPoint hm
  have hmul : beta * silver < beta * evenFixedPoint m := by
    exact mul_lt_mul_of_pos_left hlt hbeta
  simp only [evenFixedPointTransverseDelta]
  linarith

theorem tendsto_scaled_evenFixedPointTransversePerturbation :
    Filter.Tendsto
      (fun m : ℕ =>
        spectralBase ^ (2 * m) * evenFixedPointTransversePerturbation m)
      Filter.atTop (nhds (-8)) := by
  have hbs : beta * silver = 2 := silver_identities.2.1
  have h := tendsto_scaled_evenFixedPoint_sub_silver.const_mul (-beta)
  have hval : -beta * (4 * silver) = -8 := by linear_combination (-4 : ℝ) * hbs
  rw [hval] at h
  refine h.congr ?_
  intro m
  rw [evenFixedPointTransversePerturbation_eq]
  ring

theorem tendsto_evenFixedPointTransverseDelta :
    Filter.Tendsto evenFixedPointTransverseDelta Filter.atTop (nhds (-1)) := by
  have hbs : beta * silver = 2 := silver_identities.2.1
  have h := (tendsto_evenFixedPoint.const_mul beta).const_sub (1 : ℝ)
  have hval : (1 : ℝ) - beta * silver = -1 := by linear_combination -hbs
  rw [hval] at h
  exact h.congr fun m => rfl

theorem tendsto_evenFixedPoint_cutoff_signed :
    Filter.Tendsto
      (fun m : ℕ =>
        (((2 * m : ℕ) : ℝ) *
          ratio (evenFixedPointTransverseDelta m) (2 * m)) /
            spectralBase ^ (2 * m))
      Filter.atTop (nhds (-(1 / 2 : ℝ))) := by
  have hsign : ∀ m : ℕ,
      -1 + evenFixedPointTransversePerturbation m = evenFixedPointTransverseDelta m := by
    intro m
    simp only [evenFixedPointTransversePerturbation, evenFixedPointTransverseDelta]
    ring
  have h := tendsto_even_moving_pole_signed (c := (-8 : ℝ)) (by norm_num)
    tendsto_scaled_evenFixedPointTransversePerturbation
  have hval : (4 : ℝ) / (-8) = -(1 / 2 : ℝ) := by norm_num
  rw [hval] at h
  refine h.congr ?_
  intro m
  rw [hsign m]

theorem tendsto_evenFixedPoint_cutoff :
    Filter.Tendsto
      (fun m : ℕ =>
        (((2 * m : ℕ) : ℝ) *
          |ratio (evenFixedPointTransverseDelta m) (2 * m)|) /
            spectralBase ^ (2 * m))
      Filter.atTop (nhds (1 / 2 : ℝ)) := by
  have hsign : ∀ m : ℕ,
      -1 + evenFixedPointTransversePerturbation m = evenFixedPointTransverseDelta m := by
    intro m
    simp only [evenFixedPointTransversePerturbation, evenFixedPointTransverseDelta]
    ring
  have h := tendsto_even_moving_pole (c := (-8 : ℝ)) (by norm_num)
    tendsto_scaled_evenFixedPointTransversePerturbation
  have hval : (4 : ℝ) / |(-8 : ℝ)| = (1 / 2 : ℝ) := by norm_num
  rw [hval] at h
  refine h.congr ?_
  intro m
  rw [hsign m]

end MetallicCutoff
