/-
Cubic-silver finite-row crossover, Phase B1: relative normalized center
remainder transfer.

SilverFiniteRowRemainder proves the exact decomposition centerRemainder =
(deviationVariation * fixedPointFactor + centerError * (fixedPointFactor -
3*alpha^2) - delta^3) / (3*alpha). This module defines the moving crossover
scale / mu-shift / delta generated by the center error, records that they tend
to zero, and proves the HONEST transfer: if the relative deviationVariation term
tends to zero, then the normalized centerRemainder tends to zero.

This phase does NOT prove the missing relative deviationVariation estimate, and
does NOT add an unconditional spectral lower bound for centerError.
-/
import RequestProject.SilverFiniteRowRemainder

open scoped Topology

namespace SilverFiniteRow

noncomputable def movingCrossoverScale
    (N : Nat) (alpha : Real) : Real :=
  SilverCrossover.crossoverScale alpha (centerError N alpha)

noncomputable def movingMuShift
    (N : Nat) (alpha lambda : Real) : Real :=
  lambda * movingCrossoverScale N alpha / alpha

noncomputable def movingDelta
    (N : Nat) (alpha y : Real) : Real :=
  movingCrossoverScale N alpha * y

noncomputable def relativeDeviationVariation
    (N : Nat) (alpha lambda y : Real) : Real :=
  |deviationVariation N alpha
      (1 + movingMuShift N alpha lambda)
      (movingDelta N alpha y)| /
    |centerError N alpha|

noncomputable def relativeCenterRemainder
    (N : Nat) (alpha lambda y : Real) : Real :=
  |centerRemainder N alpha
      (movingMuShift N alpha lambda)
      (movingDelta N alpha y)| /
    (alpha * |centerError N alpha|)

theorem tendsto_movingCrossoverScale
    {alpha : Real} (halpha : 0 < alpha) :
    Filter.Tendsto
      (fun N : Nat => movingCrossoverScale N alpha)
      Filter.atTop (nhds 0) := by
  have habs : Filter.Tendsto
      (fun N : Nat => |centerError N alpha|) Filter.atTop (nhds 0) := by
    simpa using (tendsto_centerError halpha).abs
  have hmul : Filter.Tendsto
      (fun N : Nat => alpha * |centerError N alpha|)
      Filter.atTop (nhds 0) := by
    simpa using habs.const_mul alpha
  simpa [movingCrossoverScale, SilverCrossover.crossoverScale] using hmul.sqrt

theorem tendsto_movingMuShift
    {alpha lambda : Real} (halpha : 0 < alpha) :
    Filter.Tendsto
      (fun N : Nat => movingMuShift N alpha lambda)
      Filter.atTop (nhds 0) := by
  have h := ((tendsto_movingCrossoverScale halpha).const_mul lambda).div_const alpha
  simpa [movingMuShift] using h

theorem tendsto_movingDelta
    {alpha y : Real} (halpha : 0 < alpha) :
    Filter.Tendsto
      (fun N : Nat => movingDelta N alpha y)
      Filter.atTop (nhds 0) := by
  have h := (tendsto_movingCrossoverScale halpha).mul_const y
  simpa [movingDelta] using h

theorem eventually_moving_affineInput_pos
    {alpha lambda y : Real} (halpha : 0 < alpha) :
    ∀ᶠ N in Filter.atTop,
      0 < affineInput alpha
        (1 + movingMuShift N alpha lambda)
        (alpha + movingDelta N alpha y) := by
  have hmu := tendsto_movingMuShift (alpha := alpha) (lambda := lambda) halpha
  have hd := tendsto_movingDelta (alpha := alpha) (y := y) halpha
  have h1 : Filter.Tendsto
      (fun N : Nat =>
        alpha ^ 3 +
          3 * (1 + movingMuShift N alpha lambda) * alpha ^ 2 *
            movingDelta N alpha y)
      Filter.atTop (nhds (alpha ^ 3 + 3 * (1 + 0) * alpha ^ 2 * 0)) :=
    tendsto_const_nhds.add
      ((((tendsto_const_nhds.add hmu).const_mul 3).mul_const (alpha ^ 2)).mul hd)
  have h2 : alpha ^ 3 + 3 * (1 + (0 : Real)) * alpha ^ 2 * 0 = alpha ^ 3 := by
    ring
  rw [h2] at h1
  have hin : Filter.Tendsto
      (fun N : Nat =>
        affineInput alpha
          (1 + movingMuShift N alpha lambda)
          (alpha + movingDelta N alpha y))
      Filter.atTop (nhds (alpha ^ 3)) := by
    refine h1.congr fun N => ?_
    simp only [affineInput, SilverCrossover.affineIntercept,
      SilverCrossover.affineSlope]
    ring
  exact hin.eventually
    (eventually_gt_nhds (show (0 : Real) < alpha ^ 3 by positivity))

theorem tendsto_moving_fixedPointFactor
    {alpha lambda y : Real} (halpha : 0 < alpha) :
    Filter.Tendsto
      (fun N : Nat =>
        fixedPointFactor alpha
          (1 + movingMuShift N alpha lambda)
          (movingDelta N alpha y))
      Filter.atTop (nhds (3 * alpha ^ 2)) := by
  have hmu := tendsto_movingMuShift (alpha := alpha) (lambda := lambda) halpha
  have hd := tendsto_movingDelta (alpha := alpha) (y := y) halpha
  have h1 : Filter.Tendsto
      (fun N : Nat =>
        alpha ^ 3 +
          3 * (1 + movingMuShift N alpha lambda) * alpha ^ 2 *
            movingDelta N alpha y)
      Filter.atTop (nhds (alpha ^ 3 + 3 * (1 + 0) * alpha ^ 2 * 0)) :=
    tendsto_const_nhds.add
      ((((tendsto_const_nhds.add hmu).const_mul 3).mul_const (alpha ^ 2)).mul hd)
  have h2 : alpha ^ 3 + 3 * (1 + (0 : Real)) * alpha ^ 2 * 0 = alpha ^ 3 := by
    ring
  rw [h2] at h1
  have hin : Filter.Tendsto
      (fun N : Nat =>
        affineInput alpha
          (1 + movingMuShift N alpha lambda)
          (alpha + movingDelta N alpha y))
      Filter.atTop (nhds (alpha ^ 3)) := by
    refine h1.congr fun N => ?_
    simp only [affineInput, SilverCrossover.affineIntercept,
      SilverCrossover.affineSlope]
    ring
  have hval : ((alpha ^ 3 : Real)) ^ ((3 : Real)⁻¹) = alpha := by
    rw [← Real.rpow_natCast alpha 3, ← Real.rpow_mul halpha.le]
    norm_num
  have hL : Filter.Tendsto
      (fun N : Nat =>
        limitingMap alpha
          (1 + movingMuShift N alpha lambda)
          (alpha + movingDelta N alpha y))
      Filter.atTop (nhds alpha) := by
    have hc : ContinuousAt (fun x : Real => x ^ ((3 : Real)⁻¹)) (alpha ^ 3) :=
      Real.continuousAt_rpow_const _ _ (Or.inr (by norm_num))
    have hcomp := hc.tendsto.comp hin
    rw [hval] at hcomp
    simpa [limitingMap, Function.comp_def] using hcomp
  have hz : Filter.Tendsto
      (fun N : Nat => alpha + movingDelta N alpha y)
      Filter.atTop (nhds alpha) := by
    simpa using tendsto_const_nhds.add hd
  have hsum := (hz.mul hz).add ((hz.mul hL).add (hL.mul hL))
  have h3 : (3 : Real) * alpha ^ 2 =
      alpha * alpha + (alpha * alpha + alpha * alpha) := by ring
  rw [h3]
  refine hsum.congr fun N => ?_
  simp only [fixedPointFactor]
  ring

theorem relativeCenterRemainder_le
    {N : Nat} {alpha lambda y : Real}
    (halpha : 0 < alpha) (herror : centerError N alpha ≠ 0) :
    relativeCenterRemainder N alpha lambda y ≤
      relativeDeviationVariation N alpha lambda y *
          |fixedPointFactor alpha
            (1 + movingMuShift N alpha lambda)
            (movingDelta N alpha y)| / (3 * alpha ^ 2) +
        |fixedPointFactor alpha
            (1 + movingMuShift N alpha lambda)
            (movingDelta N alpha y) - 3 * alpha ^ 2| /
          (3 * alpha ^ 2) +
        movingCrossoverScale N alpha * |y| ^ 3 / (3 * alpha) := by
  have hE : 0 < |centerError N alpha| := abs_pos.mpr herror
  have hs2 : movingCrossoverScale N alpha ^ 2 = alpha * |centerError N alpha| :=
    SilverCrossover.crossoverScale_sq halpha.le
  have hsnn : 0 ≤ movingCrossoverScale N alpha := Real.sqrt_nonneg _
  have hDabs : |movingDelta N alpha y| ^ 3 =
      movingCrossoverScale N alpha ^ 3 * |y| ^ 3 := by
    rw [movingDelta, abs_mul, abs_of_nonneg hsnn, mul_pow]
  simp only [relativeCenterRemainder, relativeDeviationVariation]
  rw [centerRemainder_decomposition]
  set V := deviationVariation N alpha (1 + movingMuShift N alpha lambda)
    (movingDelta N alpha y)
  set Q := fixedPointFactor alpha (1 + movingMuShift N alpha lambda)
    (movingDelta N alpha y)
  set E := centerError N alpha
  set s := movingCrossoverScale N alpha
  have hnum : |V * Q + E * (Q - 3 * alpha ^ 2) - movingDelta N alpha y ^ 3| ≤
      |V| * |Q| + |E| * |Q - 3 * alpha ^ 2| + s ^ 3 * |y| ^ 3 := by
    have h1 : |V * Q + E * (Q - 3 * alpha ^ 2) - movingDelta N alpha y ^ 3| ≤
        |V * Q + E * (Q - 3 * alpha ^ 2)| + |movingDelta N alpha y ^ 3| := by
      have h := abs_add_le (V * Q + E * (Q - 3 * alpha ^ 2))
        (-(movingDelta N alpha y ^ 3))
      rwa [← sub_eq_add_neg, abs_neg] at h
    have h2 : |V * Q + E * (Q - 3 * alpha ^ 2)| ≤
        |V| * |Q| + |E| * |Q - 3 * alpha ^ 2| := by
      have h := abs_add_le (V * Q) (E * (Q - 3 * alpha ^ 2))
      rwa [abs_mul, abs_mul] at h
    have h3 : |movingDelta N alpha y ^ 3| = s ^ 3 * |y| ^ 3 := by
      rw [abs_pow]; exact hDabs
    linarith
  have hRHS : |V| / |E| * |Q| / (3 * alpha ^ 2) +
        |Q - 3 * alpha ^ 2| / (3 * alpha ^ 2) + s * |y| ^ 3 / (3 * alpha) =
      (|V| * |Q| + |E| * |Q - 3 * alpha ^ 2| + s ^ 3 * |y| ^ 3) /
        (3 * alpha * (alpha * |E|)) := by
    have hs3 : s ^ 3 = s * (alpha * |E|) := by
      rw [← hs2]; ring
    rw [hs3]
    have hEne : |E| ≠ 0 := ne_of_gt hE
    have hane : alpha ≠ 0 := ne_of_gt halpha
    field_simp
  rw [hRHS, abs_div, abs_of_pos (show (0 : Real) < 3 * alpha by linarith),
    div_div]
  have hden : (0 : Real) < 3 * alpha * (alpha * |E|) := by positivity
  exact div_le_div_of_nonneg_right hnum hden.le

theorem tendsto_relativeCenterRemainder_of_relativeDeviationVariation
    {alpha lambda y : Real} (halpha : 0 < alpha)
    (herror : ∀ᶠ N in Filter.atTop,
      centerError N alpha ≠ 0)
    (hvariation : Filter.Tendsto
      (fun N : Nat => relativeDeviationVariation N alpha lambda y)
      Filter.atTop (nhds 0)) :
    Filter.Tendsto
      (fun N : Nat => relativeCenterRemainder N alpha lambda y)
      Filter.atTop (nhds 0) := by
  have hQ := tendsto_moving_fixedPointFactor
    (alpha := alpha) (lambda := lambda) (y := y) halpha
  have hQabs : Filter.Tendsto
      (fun N : Nat =>
        |fixedPointFactor alpha (1 + movingMuShift N alpha lambda)
          (movingDelta N alpha y)|)
      Filter.atTop (nhds (3 * alpha ^ 2)) := by
    have h := hQ.abs
    rwa [abs_of_nonneg (show (0 : Real) ≤ 3 * alpha ^ 2 by positivity)] at h
  have h1 : Filter.Tendsto
      (fun N : Nat =>
        relativeDeviationVariation N alpha lambda y *
          |fixedPointFactor alpha (1 + movingMuShift N alpha lambda)
            (movingDelta N alpha y)| / (3 * alpha ^ 2))
      Filter.atTop (nhds 0) := by
    simpa using (hvariation.mul hQabs).div_const (3 * alpha ^ 2)
  have h2 : Filter.Tendsto
      (fun N : Nat =>
        |fixedPointFactor alpha (1 + movingMuShift N alpha lambda)
          (movingDelta N alpha y) - 3 * alpha ^ 2| / (3 * alpha ^ 2))
      Filter.atTop (nhds 0) := by
    have h := (hQ.sub_const (3 * alpha ^ 2)).abs
    rw [sub_self, abs_zero] at h
    simpa using h.div_const (3 * alpha ^ 2)
  have h3 : Filter.Tendsto
      (fun N : Nat => movingCrossoverScale N alpha * |y| ^ 3 / (3 * alpha))
      Filter.atTop (nhds 0) := by
    simpa using
      ((tendsto_movingCrossoverScale halpha).mul_const (|y| ^ 3)).div_const
        (3 * alpha)
  have hbound : Filter.Tendsto
      (fun N : Nat =>
        relativeDeviationVariation N alpha lambda y *
            |fixedPointFactor alpha (1 + movingMuShift N alpha lambda)
              (movingDelta N alpha y)| / (3 * alpha ^ 2) +
          |fixedPointFactor alpha (1 + movingMuShift N alpha lambda)
              (movingDelta N alpha y) - 3 * alpha ^ 2| / (3 * alpha ^ 2) +
          movingCrossoverScale N alpha * |y| ^ 3 / (3 * alpha))
      Filter.atTop (nhds 0) := by
    simpa using (h1.add h2).add h3
  refine squeeze_zero' ?_ ?_ hbound
  · filter_upwards with N
    simp only [relativeCenterRemainder]
    exact div_nonneg (abs_nonneg _) (mul_nonneg halpha.le (abs_nonneg _))
  · filter_upwards [herror] with N hN
    exact relativeCenterRemainder_le halpha hN

end SilverFiniteRow
